version: "3.3"
services: 
  api:
    container_name: NLNS-api
    build: ./
    ports:
      - 8000:80
    env_file: 
      - .env
    depends_on:
      - db

  db:
    container_name: NLNS-db
    image: postgres:12
    volumes:
      - ./app-db-data:/var/lib/postgresql/data
    env_file: 
      - .env
    ports: 
      - 5432:5432
    environment: 
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always

  pgadmin:
    container_name: NLNS-pgadmin
    image: dpage/pgadmin4
    env_file: 
      - .env
    ports:
      - 5050:5050
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
